name: Check action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Test runner connexion
      uses: mnival/sshd-action@main
      with:
        ssh_host: ${{ secrets.SSH_HOST }}
        ssh_user: ${{ secrets.SSH_USER }}
        ssh_key: ${{ secrets.SSH_KEY }}
        ssh_remote_command: ssh runner@127.0.0.1 -oPort=2200
